server:
  port: 8080

api:
  url: https://loripsum.net/api/


spring:
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: ${BROKER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
