version: "3.8"

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  postgres:
    image: postgres
    container_name: consumer-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=consumer-db
      - POSTGRES_USER=consumer
      - POSTGRES_PASSWORD=consumer
    healthcheck:
      test: [ "CMD", "pg_isready -U consumer" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: